openapi: 3.0.0
info:
  title: '123'
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Credit-Information:
      title: Credit-Information
      type: object
      properties:
        firstname:
          type: string
        last name:
          type: string
        sumCredit:
          type: number
          format: double
        interestRate:
          type: number
          format: double
        loanPeriod:
          type: integer
        dateCredit:
          type: string
          format: date
    OutInformationAboutCredit:
      title: OutInformationAboutCredit
      type: object
      properties:
        datePayment:
          type: string
          format: date
        monthlyPayment:
          type: number
          format: double
        repaymentAmount:
          type: number
          format: double
        percent:
          type: number
          format: double
        sumCredit:
          type: number
          format: double
  securitySchemes: {}
